In [ ]:
import pandas as pd

In [ ]:
import pandas as pd

# File paths for your CSVs
file_paths = ['/content/Patient_info.csv', '/content/BASELINE_ABP.csv', '/content/SEPSIS.csv']

# Read CSVs into a list of DataFrames
dfs = [pd.read_csv(file) for file in file_paths]
merged_df = pd.merge(dfs[1], dfs[0], on='admissionid', how='outer')
merged_df = pd.merge(merged_df, dfs[2], on='admissionid', how='outer')

In [ ]:
merged_df = merged_df.drop('Unnamed: 0_x', axis=1)

In [ ]:
merged_df = merged_df.drop('Unnamed: 0_y', axis=1)

In [ ]:
merged_df

,admissionid,value,urgency,lengthofstay,gender,agegroup,weightgroup,sepsis_at_admission,sepsis_ic
0,0,68.0,0,42,Vrouw,80+,60-69,NaN,NaN
1,1,69.0,0,26,Man,60-69,70-79,0.0,0.0
2,2,73.0,1,23,Man,60-69,90-99,0.0,0.0
3,3,0.0,0,23,Man,50-59,90-99,NaN,NaN
4,4,62.0,0,50,Man,70-79,70-79,0.0,0.0
...,...,...,...,...,...,...,...,...,...
23101,22244,NaN,1,1,Vrouw,18-39,59-,NaN,NaN
23102,5779,NaN,1,8,Vrouw,40-49,70-79,1.0,1.0
23103,7127,NaN,0,2,Man,50-59,80-89,NaN,NaN
23104,14522,NaN,0,45,Man,40-49,100-109,0.0,0.0
23105,22598,NaN,0,41,Man,50-59,80-89,NaN,NaN

In [ ]:
merged_df= merged_df.rename(columns={'value': 'Baseline_ABP'})

In [ ]:
merged_df['Baseline_ABP'].dtype

dtype('float64')

In [ ]:
merged_df
merged_df['sepsis_at_admission']=merged_df['sepsis_at_admission'].fillna(0)
merged_df['sepsis_ic']=merged_df['sepsis_ic'].fillna(0)

In [ ]:
fill_value_for_abp=merged_df['Baseline_ABP'].mean()

In [ ]:
merged_df['Baseline_ABP']=merged_df['Baseline_ABP'].fillna(int(fill_value_for_abp))

In [ ]:
merged_df

,admissionid,Baseline_ABP,urgency,lengthofstay,gender,agegroup,weightgroup,sepsis_at_admission,sepsis_ic
0,0,68.0,0,42,Vrouw,80+,60-69,0.0,0.0
1,1,69.0,0,26,Man,60-69,70-79,0.0,0.0
2,2,73.0,1,23,Man,60-69,90-99,0.0,0.0
3,3,0.0,0,23,Man,50-59,90-99,0.0,0.0
4,4,62.0,0,50,Man,70-79,70-79,0.0,0.0
...,...,...,...,...,...,...,...,...,...
23101,22244,76.0,1,1,Vrouw,18-39,59-,0.0,0.0
23102,5779,76.0,1,8,Vrouw,40-49,70-79,1.0,1.0
23103,7127,76.0,0,2,Man,50-59,80-89,0.0,0.0
23104,14522,76.0,0,45,Man,40-49,100-109,0.0,0.0
23105,22598,76.0,0,41,Man,50-59,80-89,0.0,0.0

In [ ]:
merged_df['gender'].unique()

array(['Vrouw', 'Man', nan], dtype=object)

In [ ]:
merged_df['weightgroup'].unique()

array(['60-69', '70-79', '90-99', '100-109', '80-89', '59-', nan, '110+'],
      dtype=object)

In [ ]:
merged_df['agegroup'].unique()

array(['80+', '60-69', '50-59', '70-79', '18-39', '40-49'], dtype=object)

In [ ]:
merged_df_one_hot_encoded = pd.get_dummies(merged_df, columns=['gender','weightgroup','agegroup'], dummy_na=False) #THİS IS WHERE WE GET ONE HOT ENCODED DATA

In [ ]:
merged_df_one_hot_encoded

,admissionid,Baseline_ABP,urgency,lengthofstay,sepsis_at_admission,sepsis_ic,gender_Man,gender_Vrouw,weightgroup_100-109,weightgroup_110+,...,weightgroup_60-69,weightgroup_70-79,weightgroup_80-89,weightgroup_90-99,agegroup_18-39,agegroup_40-49,agegroup_50-59,agegroup_60-69,agegroup_70-79,agegroup_80+
0,0,68.0,0,42,0.0,0.0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,1
1,1,69.0,0,26,0.0,0.0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
2,2,73.0,1,23,0.0,0.0,1,0,0,0,...,0,0,0,1,0,0,0,1,0,0
3,3,0.0,0,23,0.0,0.0,1,0,0,0,...,0,0,0,1,0,0,1,0,0,0
4,4,62.0,0,50,0.0,0.0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23101,22244,76.0,1,1,0.0,0.0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
23102,5779,76.0,1,8,1.0,1.0,0,1,0,0,...,0,1,0,0,0,1,0,0,0,0
23103,7127,76.0,0,2,0.0,0.0,1,0,0,0,...,0,0,1,0,0,0,1,0,0,0
23104,14522,76.0,0,45,0.0,0.0,1,0,1,0,...,0,0,0,0,0,1,0,0,0,0
23105,22598,76.0,0,41,0.0,0.0,1,0,0,0,...,0,0,1,0,0,0,1,0,0,0

In [ ]:
merged_df_one_hot_encoded1=merged_df_one_hot_encoded.drop('lengthofstay',axis=1)

In [ ]:
merged_df_one_hot_encoded1.to_csv('Merged_v1.csv')